include: 'http://dev.zxteam.net/maxim.anurin/gitlab-pipelines/raw/master/node/public-lib.yml'

cache:
  paths:
    - node_modules/

test:
  stage: test
  image: docker.registry.zxteam.net/pub/docker/build/node10.protoc-mysqlcli-psqlcli:1
  dependencies:
    - build
  variables:
    GIT_STRATEGY: none
    TEST_DB_URL: 'postgres://devtest@postgres:5432/emptytestdb'
  services:
    - name: docker.registry.zxteam.net/pub/docker/test/postgres10:1
      alias: postgres
  script:
    - npm run prepare:devdb
    - npm run test
